#!/usr/bin/env node
// Regenerate every file derived from core/.
//
// Three derived files, three reasons they exist as copies:
//   1. adapters/claude-code/core/*.js — Claude Code org sync packages the
//      plugin directory alone, so it cannot require its way up to core/.
//   2. adapters/claude-code/skills/codequiz/SKILL.md — needs frontmatter on top
//      of core/rules.md, and Claude Code has no include mechanism.
//   3. adapters/codex/AGENTS.snippet.md — Codex carries the rules in AGENTS.md
//      instead of a skill.
//
// core/ stays the single source. Run `npm run sync` after editing it;
// tests/sync.test.js fails if the copies drift.

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const PLUGIN = path.join(ROOT, 'adapters', 'claude-code');
const SKILL = path.join(PLUGIN, 'skills', 'codequiz', 'SKILL.md');
const CODEX_AGENTS = path.join(ROOT, 'adapters', 'codex', 'AGENTS.snippet.md');
const VENDORED = ['decide.js', 'hook.js', 'state.js'];

const read = (...p) => fs.readFileSync(path.join(ROOT, ...p), 'utf8');
const banner = (name) =>
  `// GENERATED by scripts/sync.js from core/${name} — edit that file, then run \`npm run sync\`.\n`;

// Everything from the opening `---` through the closing `---`, inclusive.
function frontmatter(text) {
  const m = /^---\n[\s\S]*?\n---\n/.exec(text);
  if (!m) throw new Error(`${SKILL} has no frontmatter`);
  return m[0];
}

// [absolute path, what it should contain] for every generated file.
function targets() {
  const rules = read('core', 'rules.md').trim();
  const out = [
    [SKILL, frontmatter(fs.readFileSync(SKILL, 'utf8')) + '\n' + rules + '\n'],
    [CODEX_AGENTS, `<!-- GENERATED by scripts/sync.js from core/rules.md -->\n\n${rules}\n`],
  ];
  for (const name of VENDORED) {
    // Drop the shebang: these copies are required, never executed, and a
    // banner above `#!` is a syntax error.
    out.push([
      path.join(PLUGIN, 'core', name),
      banner(name) + read('core', name).replace(/^#!.*\n/, ''),
    ]);
  }
  return out;
}

if (require.main === module) {
  for (const [file, body] of targets()) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, body);
    console.log(`synced ${path.relative(ROOT, file)}`);
  }
}

module.exports = { ROOT, targets };
