#!/usr/bin/env node
// Regenerate the Claude Code adapter's copies of core/.
//
// Two reasons the plugin carries copies instead of reaching up into core/:
//   1. Claude Code org sync packages each plugin directory on its own, so a
//      `../../../core` require would resolve to nothing for those users.
//   2. SKILL.md needs frontmatter on top of core/rules.md and Claude Code has
//      no include mechanism.
//
// core/ stays the single source. Run `npm run sync` after editing it;
// tests/sync.test.js fails if the copies drift.

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const PLUGIN = path.join(ROOT, 'adapters', 'claude-code');
const SKILL = path.join(PLUGIN, 'skills', 'codequiz', 'SKILL.md');
const VENDORED = ['decide.js', 'state.js'];

const banner = (name) =>
  `// GENERATED by scripts/sync.js from core/${name} — edit that file, then run \`npm run sync\`.\n`;

// Everything from the opening `---` through the closing `---`, inclusive.
function frontmatter(text) {
  const m = /^---\n[\s\S]*?\n---\n/.exec(text);
  if (!m) throw new Error(`${SKILL} has no frontmatter`);
  return m[0];
}

// [absolute path, what it should contain] for every generated file.
function targets() {
  const out = [
    [SKILL, frontmatter(fs.readFileSync(SKILL, 'utf8')) + '\n' + fs.readFileSync(path.join(ROOT, 'core', 'rules.md'), 'utf8').trim() + '\n'],
  ];
  for (const name of VENDORED) {
    // Drop the shebang: these copies are required, never executed, and a
    // banner above `#!` is a syntax error.
    const body = fs.readFileSync(path.join(ROOT, 'core', name), 'utf8').replace(/^#!.*\n/, '');
    out.push([path.join(PLUGIN, 'core', name), banner(name) + body]);
  }
  return out;
}

if (require.main === module) {
  for (const [file, body] of targets()) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, body);
    console.log(`synced ${path.relative(ROOT, file)}`);
  }
}

module.exports = { ROOT, targets };
